{% set version = "1.2-10" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-aer
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/AER_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/AER/AER_{{ version }}.tar.gz
  sha256: 650a5fb54a8addf8c86f1e0f88f4fac5349731bc5bf34762a991022140eedbdc

build:
  merge_build_host: True  # [win]
  number: 2
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - r-base
    - r-formula >=0.2_0
    - r-car >=2.0_19
    - r-lmtest
    - r-sandwich >=2.4_0
    - r-survival >=2.37_5
    - r-zoo
  run:
    - r-base
    - r-formula >=0.2_0
    - r-car >=2.0_19
    - r-lmtest
    - r-sandwich >=2.4_0
    - r-survival >=2.37_5
    - r-zoo

test:
  commands:
    - $R -e "library('AER')"           # [not win]
    - "\"%R%\" -e \"library('AER')\""  # [win]

about:
  home: https://CRAN.R-project.org/package=AER
  license: GPL-2.0-or-later
  summary: Functions, data sets, examples, demos, and vignettes for the book Christian Kleiber
    and Achim Zeileis (2008), Applied Econometrics with R, Springer-Verlag, New York.
    ISBN 978-0-387-77316-2. (See the vignette "AER" for a package overview.)
  license_family: GPL3
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3

extra:
  recipe-maintainers:
    - conda-forge/r
