appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
provider: {win: azure}
travis:
  secure: {BINSTAR_TOKEN: VWH5lwd9y2Q6Urzp2LpeZ9HlHfqzknbryfHYie8zVfboLvIbwntZT7RO1TVIgFPH2zoKndsTVtcS9Si9/NsAZelahhOiwCpBMuTpaNdjV/fGZ5E06F/471GlEM6+4qdw4G0fal7rYDrsMYukPTn4Y5tRR5eW5AE6uXS6n7FRN1g2Xa8QvBnGiB5gTO74XSjRpjqPNaEeVGWJktGmfHGL8DNqxUz15xTAaZphp/mCczW6PfBTj2mIAbTLf4IHwRWu/ikTHsSOYjx3/3yezwzCWZf4KkCD++LhGWFqn68xZKM3nJekTDuc1aaZMmkfx875JCefIy2jCBs3LRgCz2jt8Z0nBNZjh0k2jkLIuF1pCjwCurDRrU7lHR9ierM1U/x2wECfj33y2b9NGDPY1U/CYSk3GwnH8KCawqxTFEjSPYv4jHXo1pOZD1grsrr7MhgdRblsklhs5DSok+crAbbZkNHFCUzrzerJdYs4dkRGDtRdh3v1hr6X2vtUwyXHg+8Kpz8TCagF+6HxIyG8E1TPzDJD5oDWuwRyQC9UYAdMUyMCPwepaU5taYMbS3x4nYiIp2zHrbJsEAd4w85QxEezl9ZCsIE1pKGzY2aPZzh7s+lF0mPtMIQ/DcP/eY8WS+YBh1MhvyAmFUXZ8aeFHwP55ro64AeZoh0Av3qAlVArtPo=}
bot:
  automerge: true
